name: tiled_custom_type_generator
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  build: 
  analyzer: ^5.6.0
  build_config: ^1.1.1
  source_gen: ^1.2.7
  build_resolvers: ^2.2.0
  meta: ^1.8.0
  glob: ^2.1.1
  json_annotation: ^4.8.0
  tiled_project:
    path: ../tiled_project
  tiled_custom_type_annotation:
    path: ../tiled_custom_type_annotation
  json_serializable: ^6.6.1
  generic_reader: ^0.3.0
  tiled:
    path: ../tiled

dev_dependencies:
  build_runner: ^2.3.3
  lints: '>=1.0.0 <3.0.0'