name: tiled_custom_type_generator
version: 0.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  build:
  tiled:
  analyzer: ^5.6.0
  build_config: ^1.1.1
  source_gen: ^1.2.7
  flutter:
    sdk: flutter
  build_resolvers: ^2.2.0
flutter:
  generate: true
  uses-material-design: false

dev_dependencies:
  lints: '>=1.0.0 <3.0.0'

dependency_overrides:
  tiled:
    path: ../tiled
