name: tiled
version: 0.10.1
description: A Dart Tiled library. Parse your TMX files into useful representations. Compatible with Flame.
homepage: https://github.com/flame-engine/tiled.dart

environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  archive: ^3.3.0
  collection: ^1.16.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  meta: ^1.7.0
  xml: ^6.1.0

dev_dependencies:
  build_runner: ^2.3.3
  dartdoc: ^6.1.5
  flame_lint: ^0.2.0
  test: any

