name: custom_type_example
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  tiled_custom_type_generator:
    path: ../
  tiled:

dev_dependencies:
  build_runner: ^2.0.0

dependency_overrides:
  tiled:
    path: ../../tiled