name: tiled_custom_type_annotation
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none"
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  json_annotation: ^4.8.1
  meta: ^1.8.0
  tiled: 0.10.1

dependency_overrides:
  tiled:
    git:
      url: git@github.com:natebot13/tiled.dart.git
      path: packages/tiled

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
