name: tiled_custom_type_annotation
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none"
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  json_annotation: ^4.8.0
  meta: ^1.8.0
  tiled:
    path: ../tiled

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
